# Copyright 2023 Michael Tietz (MT Software) <mtietz@mt-software.de>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
from collections import defaultdict
from copy import copy

from odoo import _, api, fields, models, tools
from odoo.exceptions import ValidationError
from odoo.osv import expression
from odoo.tools import split_every

from odoo.addons.queue_job.job import identity_exact
from odoo.addons.stock.models.stock_move import PROCUREMENT_PRIORITIES

from .stock_location_orderpoint_strategy import StockLocationOrderpointStrategy
from .tools import MovesTouchTracker


class StockLocationOrderpoint(models.Model):
    _name = "stock.location.orderpoint"
    _inherit = ["stock.exclude.location.mixin"]
    _description = "Stock location orderpoint"
    _order = "priority desc, sequence"
    _check_company_auto = True

    name = fields.Char(
        copy=False,
        required=True,
        readonly=True,
        default=lambda self: self.env["ir.sequence"].next_by_code(
            "stock.location.orderpoint"
        ),
    )
    company_id = fields.Many2one(
        "res.company",
        "Company",
        required=True,
        default=lambda self: self.env.company,
    )
    location_id = fields.Many2one(
        "stock.location",
        "Location",
        ondelete="cascade",
        required=True,
        check_company=True,
    )
    trigger = fields.Selection(
        [
            ("auto", "Auto/realtime"),
            ("manual", "Manual"),
            ("cron", "Scheduled"),
        ],
        default="auto",
        required=True,
        help="Auto/realtime orderpoints are triggered on new moves\n"
        "Manual orderpoints are triggered via the orderpoints' view\n"
        "Scheduled orderpoints are triggered via scheduled actions per location",
    )
    replenish_method = fields.Selection(
        [("fill_up", "Fill up")],
        default="fill_up",
        required=True,
        help="Defines how the qty to replenish gets computed\n"
        "Fill up = The replenishment will be triggered when a move is waiting availability "
        "and forecast quantity is negative at the location (i.e. min=0). "
        "The replenished quantity will bring back the forecast quantity to 0 (i.e. max=0) "
        "but will be limited to what is available at the source location "
        "to plan only reservable replenishment moves",
    )
    sequence = fields.Integer(default=10)
    route_id = fields.Many2one(
        "stock.route",
        string="Preferred Route",
        domain="[('rule_ids.location_dest_id', 'in', [location_id])]",
    )
    group_id = fields.Many2one(
        "procurement.group",
        "Procurement Group",
        copy=False,
        help="Moves created through this orderpoint "
        "will be put in this procurement group. "
        "If none is given, the moves generated by stock rules "
        "will be grouped into one big picking.",
    )
    location_src_id = fields.Many2one(
        "stock.location", compute="_compute_location_src_id", store=True
    )
    replenish_limit_to_free_qty = fields.Boolean(
        string="Limit replenishment to free quantity at source location",
        help="If enabled, the replenishment quantity will be "
        "limited to the free quantity at the source location. ",
        default=True,
    )
    active = fields.Boolean(default=True)

    last_cron_execution = fields.Datetime(
        help="Last time this orderpoint was processed by the cron",
    )
    priority = fields.Selection(
        PROCUREMENT_PRIORITIES,
        default="0",
    )
    proc_run_async = fields.Boolean(
        string="Delay procurement execution",
        help="If enabled, procurements will be run asynchronously in delayed jobs "
        "when processing this orderpoint. Only applies to 'cron' and 'manual' triggers. "
        "If disabled, all procurements will be run in the same transaction. ",
        compute="_compute_proc_run_async",
        store=True,
        readonly=False,
        precompute=True,
    )

    _sql_constraints = [
        (
            "location_route_unique",
            "unique(location_id, route_id, company_id, replenish_method)",
            "The combination of Company, Location, Route and Replenish method must be unique",
        )
    ]

    # -------------------------------------------------------------------------
    # Validation and computed fields
    # -------------------------------------------------------------------------

    @api.constrains("location_id", "route_id")
    def _check_location_id_route_id(self):
        for orderpoint in self:
            if (
                not orderpoint.route_id
                or orderpoint.location_id
                in orderpoint.route_id.rule_ids.location_dest_id
            ):
                continue
            raise ValidationError(
                _(
                    "The selected route %(route_name)s must contain "
                    "a rule where the Destination Location is %(location_name)s"
                )
                % {
                    "route_name": orderpoint.route_id.display_name,
                    "location_name": orderpoint.location_id.display_name,
                }
            )

    @api.depends("location_id", "route_id")
    def _compute_location_src_id(self):
        for orderpoint in self:
            location = False
            if orderpoint.location_id and orderpoint.route_id:
                location = orderpoint.location_id._get_source_location_from_route(
                    orderpoint.route_id,
                    "make_to_stock",
                )
            orderpoint.location_src_id = location

    @api.depends("trigger")
    def _compute_proc_run_async(self):
        for orderpoint in self:
            orderpoint.proc_run_async = orderpoint.trigger in ("cron", "manual")

    # -------------------------------------------------------------------------
    # Orderpoint selection and domains
    # -------------------------------------------------------------------------

    def _prepare_orderpoint_domain_location(
        self, location_ids, location_field="location_id"
    ):
        """
        Returns the domain part of the location selection of _get_orderpoints
        :param list int location_ids: list of stock.location ids
        :param str location_field: location_id or location_src_id
            To create the domain searching the specific location field
        """
        ids = location_ids
        if not isinstance(ids, list):
            ids = ids.ids

        location_field = location_field or "location_id"
        return [(location_field, "parent_of", ids)]

    def _prepare_orderpoint_domain(
        self, trigger, locations=None, location_field="location_id"
    ):
        """Returns the domain for _get_orderpoints"""
        domain = [("trigger", "=", trigger)]
        if locations:
            domain = expression.AND(
                [
                    domain,
                    self._prepare_orderpoint_domain_location(locations, location_field),
                ]
            )
        return domain

    @api.model
    @tools.ormcache(
        "trigger",
        "location_field",
        'tuple(self.env.context.get("allowed_company_ids", []))',
    )
    def _get_ids_by_parent_path(self, trigger, location_field):
        """Returns a dict of orderpoint ids by their parent paths for the given
        trigger and location_field
        """
        orderpoints = self.search(self._prepare_orderpoint_domain(trigger))
        result = defaultdict(list)
        for orderpoint in orderpoints:
            result[orderpoint[location_field].parent_path].append(orderpoint.id)
        return result

    @api.model
    def _get_orderpoints(self, trigger, locations=None, location_field="location_id"):
        """Returns orderpoints selected by trigger, locations and location_field"""
        ids_by_parent_paths = self._get_ids_by_parent_path(trigger, location_field)
        ids = set()
        if locations:
            for location in locations:
                for parent_path in ids_by_parent_paths:
                    if location.parent_path.startswith(parent_path):
                        ids.update(ids_by_parent_paths[parent_path])
        else:
            # ids_by_parent_paths.values() is a list of ids. We need to flatten it
            ids = set().union(*ids_by_parent_paths.values())
        return self.browse(list(ids)).sorted()

    @api.model
    def _get_orderpoints_from_moves(self, moves, trigger="auto"):
        """Return orderpoints impacted by the given move set."""
        orderpoints = self._get_orderpoints(
            trigger, locations=moves.location_id, location_field="location_id"
        )
        return orderpoints | self._get_orderpoints(
            trigger, locations=moves.location_dest_id, location_field="location_src_id"
        )

    @api.model
    @tools.ormcache("orderpoint_id")
    def _get_consuming_moves_domain(self, orderpoint_id):
        (
            _q,
            _il,
            domain_move_out_loc,
        ) = self._get_dest_domains(orderpoint_id)
        domain = [
            ("state", "in", ("confirmed", "partially_available")),
        ]
        return expression.AND([domain_move_out_loc, domain])

    @api.model
    @tools.ormcache("orderpoint_id")
    def _get_supplying_moves_domain(self, orderpoint_id):
        (
            _q,
            domain_move_in_loc,
            _ol,
        ) = self._get_src_domains(orderpoint_id)
        domain = [
            ("state", "=", "done"),
        ]
        return expression.AND([domain_move_in_loc, domain])

    @api.model
    def _collect_products_by_orderpoint(self, moves, orderpoints, get_domain):
        """Group impacted products by orderpoint using a domain provider."""
        products_by_orderpoint = defaultdict(self.env["product.product"].browse)
        for orderpoint in orderpoints:
            moves_for_orderpoint = moves.filtered_domain(get_domain(orderpoint.id))
            if not moves_for_orderpoint:
                continue
            products_by_orderpoint[orderpoint] |= moves_for_orderpoint.mapped(
                "product_id"
            )
        return products_by_orderpoint

    @api.model
    def _get_from_move_demand(self, moves, trigger="auto"):
        """
        Return a dict of products by orderpoint to replenish the demand
        generated by the given moves. (The given moves are consuming the
        orderpoint location).
        :param moves: stock.move recordset
        :param trigger: the trigger to consider to select the orderpoints to replenish
        :return: dict {orderpoint: products}
        """
        # move from location consume order point location -> DO I've to replenish?
        orderpoints = self._get_orderpoints(
            trigger, locations=moves.location_id, location_field="location_id"
        )
        return self._collect_products_by_orderpoint(
            moves, orderpoints, self._get_consuming_moves_domain
        )

    @api.model
    def _get_from_move_supply(self, moves, trigger="auto"):
        """
        Return a dict of products by orderpoint to replenish the demand
        generated by the given moves. (The given moves are supplying the
        orderpoint source location).
        :param moves: stock.move recordset
        :param trigger: the trigger to consider to select the orderpoints to replenish
        :return: dict {orderpoint: products}
        """
        # move to src location replenish order point source location -> DO I've to replenish?
        orderpoints = self._get_orderpoints(
            trigger, locations=moves.location_dest_id, location_field="location_src_id"
        )
        return self._collect_products_by_orderpoint(
            moves, orderpoints, self._get_supplying_moves_domain
        )

    @api.model
    @tools.ormcache("orderpoint_id")
    def _get_src_domains(self, orderpoint_id):
        """Get the quant, move in and move out domains
        for the orderpoint location source and its children locations
        """
        orderpoint = self.browse(orderpoint_id)
        return orderpoint._product_model._get_domain_locations_new(
            [orderpoint.location_src_id.id]
        )

    @api.model
    @tools.ormcache("orderpoint_id")
    def _get_dest_domains(self, orderpoint_id):
        """Get the quant, move in and move out domains
        for the orderpoint location destination and its children locations
        """
        orderpoint = self.browse(orderpoint_id)
        return orderpoint._product_model._get_domain_locations_new(
            [orderpoint.location_id.id]
        )

    # -------------------------------------------------------------------------
    # Context-aware model accessors
    # -------------------------------------------------------------------------

    @property
    def _product_model(self):
        """Returns the product model in the context of the orderpoint,
        to be used to compute the quantities.
        It ensures that the context includes the excluded location domain.
        """
        self.ensure_one()
        return self.env["product.product"].with_context(
            excluded_location_domain=self.stock_excluded_location_domain
        )

    @property
    def _strategy_model(self) -> StockLocationOrderpointStrategy:
        self.ensure_one()
        if self.replenish_method == "fill_up":
            return self.env["stock.location.orderpoint.strategy.fill_up"]
        raise ValidationError(_("No strategy class available"))

    # -------------------------------------------------------------------------
    # Public triggers and orchestration
    # -------------------------------------------------------------------------

    @api.model
    def run_cron_replenishment(self, location_ids=None):
        orderpoints = self._get_orderpoints(trigger="cron", locations=location_ids)
        res = orderpoints.run_replenishment()
        orderpoints.write({"last_cron_execution": self.env.cr.now()})
        return res

    @api.model
    def run_auto_replenishment(self, products, locations, location_field="location_id"):
        """
        Run the replenishment for all given products
        Selects the right orderpoints by locations and location_field

        :param products: browse record list of product.product
        :param locations: browse record list of stock.location
        :param location_field: should be location_id or location_src_id
        """
        if not locations or not products:
            return
        orderpoints = self._get_orderpoints("auto", locations, location_field)
        orderpoints.run_replenishment(products)

    def run_replenishment(self, products=None):
        """
        Public entry point to execute the replenishment rule.

        :param products: optional recordset of product.product
            If provided, limits the computation scope.
        """
        result = self.env["stock.move"]
        processed = set()
        for orderpoint in self.sorted():
            result |= orderpoint._run_replenishment(
                products=products, processed=processed
            )
            processed.update(
                [(orderpoint.location_id.id, m.product_id.id) for m in result]
            )
        return result

    def _run_replenishment(self, products=None, processed=None):
        """
        Internal pipeline:
        1. determine candidate products
        2. compute demand (strategy)
        3. compute qty to procure and execute replenishment
           (either synchronously or via delayed jobs per product)

        Two delay mechanisms exist in this module and serve different purposes:

        - AUTO trigger: the delay happens *before* this pipeline, in stock.move,
          one job per (orderpoint, product) pair. Its goal is to avoid computing
          demand for products whose move does not actually impact any orderpoint.
          Because the delay already happened upstream, _must_delay_procurement_run()
          always returns False for AUTO orderpoints, and procurement execution is
          always synchronous here.

        - CRON / MANUAL triggers: when proc_run_async is True, one job per
          (orderpoint, product) is enqueued after demand is computed. Each job
          then handles the full remaining pipeline atomically: available qty
          computation, procurement qty decision, and execution. This ensures
          that qty availability and procurement creation are never split across
          separate transactions, and keeps the number of jobs bounded by the
          number of products with actual demand (not the total product catalogue).

        :param products: optional recordset of product.product
        :param processed: set of (location_id, product_id) tuples that have already
                          been processed
        """
        result = self.env["stock.move"]
        processed = processed or set()
        self.ensure_one()
        products = self._get_candidate_products(products)

        # filter out products that have already been processed by
        # another orderpoint to avoid redundant processing
        if products is not None and processed:
            products = products.filtered(
                lambda p: (self.location_id.id, p.id) not in processed
            )

        if not products and products is not None:
            # an empty recordset means that no products
            # are concerned by the replenishment.
            # Otherwise a None value means that we don't want
            # to limit the scope of the computation
            return result

        products = self._with_excluded_location_context(products)

        demand_data = self._compute_demand(products)

        # exclude already processed products from demand_data to avoid redundant processing
        # the filtering is done here since the demand computation could reintroduce products
        # That's the case when None is passed as products which means that the demand should
        # not be soped to a specific set of products.
        if demand_data and processed:
            demand_data = {
                pid: qty
                for pid, qty in demand_data.items()
                if (self.location_id.id, pid) not in processed
            }

        if not demand_data:
            return result

        # Delay per-product fulfillment if needed.
        # For AUTO orderpoints, _must_delay_procurement_run() always returns
        # False: they already run inside a queue.job enqueued by stock.move.
        if self._must_delay_procurement_run():
            for product_id, demand_qty in demand_data.items():
                self._enqueue_fulfill_procurement(product_id, demand_qty).delay()
            return result

        procurement_data = self._compute_procurement_qty(demand_data)
        if not procurement_data:
            return result

        procurements = self._build_procurements(procurement_data)
        if not procurements:
            return result

        result = self._execute_run_procurements(procurements)
        return self._after_replenishment(result)

    def _with_excluded_location_context(self, products):
        """Ensure product computations use orderpoint's excluded location domain."""
        if products and "excluded_location_domain" not in products.env.context:
            return products.with_context(
                excluded_location_domain=self.stock_excluded_location_domain
            )
        return products

    # -------------------------------------------------------------------------
    # Replenishment computation pipeline
    # -------------------------------------------------------------------------

    def _build_procurements(self, procurement_data):
        """Build procurement payload from computed quantities by product id."""
        self.ensure_one()
        procurement_vals = self._prepare_procurement_vals()
        return [
            self._prepare_procurement(
                self.env["product.product"].browse(product_id),
                procurement_qty,
                date_planned=False,
                proc_vals=procurement_vals,
            )
            for product_id, procurement_qty in procurement_data.items()
        ]

    def _get_candidate_products(self, products=None):
        """
        Resolve the product scope.

        Priority:
        1. explicit products
        2. strategy override
        3. default (rule-based #to be implemented if needed)

        :return: product.product recordset
        """
        return products or self._strategy_model._get_candidate_products(self)

    def _compute_demand(self, products):
        """
        Delegate to strategy.

        :return: dict {product_id: demand_qty}
        """
        return self._strategy_model._compute_demand(self, products)

    def _compute_available_quantities(self, products):
        """
        Compute available quantities for products at rule's source location.

        :return: dict {product_id: qty_available}
        """
        quant_domain, _move_in_domain, move_out_domain = self._get_src_domains(self.id)
        if len(products) < 500:
            # in query is too expensive with a large number of products,
            #  so we avoid it when possible.
            quant_domain = expression.AND(
                [quant_domain, [("product_id", "in", products.ids)]]
            )
            move_out_domain = expression.AND(
                [move_out_domain, [("product_id", "in", products.ids)]]
            )
        move_out_domain = expression.AND(
            [
                move_out_domain,
                [
                    (
                        "state",
                        "in",
                        ("confirmed", "assigned", "partially_available"),
                    )
                ],
            ]
        )
        # --- STOCK MOVE (OUTGOING) ---

        stock_move_obj = self.env["stock.move"]
        stock_move_obj._flush_search(move_out_domain)
        stock_move_obj.flush_model(["product_uom_qty"])

        move_query = stock_move_obj._where_calc(move_out_domain)
        stock_move_obj._apply_ir_rules(move_query, "read")

        move_tables, move_where, move_params = move_query.get_sql()

        move_sql = f"""
            SELECT
                {stock_move_obj._table}.product_id,
                - SUM({stock_move_obj._table}.product_uom_qty) AS qty
            FROM {move_tables}
            WHERE {move_where}
            GROUP BY {stock_move_obj._table}.product_id
        """

        # --- STOCK QUANT ---

        stock_quant_obj = self.env["stock.quant"]
        stock_quant_obj._flush_search(quant_domain)
        stock_quant_obj.flush_model(["quantity"])

        quant_query = stock_quant_obj._where_calc(quant_domain)
        stock_quant_obj._apply_ir_rules(quant_query, "read")

        quant_tables, quant_where, quant_params = quant_query.get_sql()

        quant_sql = f"""
            SELECT
                {stock_quant_obj._table}.product_id,
                SUM({stock_quant_obj._table}.quantity) AS qty
            FROM {quant_tables}
            WHERE {quant_where}
            GROUP BY {stock_quant_obj._table}.product_id
        """

        # --- FINAL UNION ---

        final_sql = f"""
            SELECT product_id, SUM(qty) AS qty
            FROM (
                {move_sql}
                UNION ALL
                {quant_sql}
            ) AS combined
            GROUP BY product_id
        """

        params = move_params + quant_params

        self.env.cr.execute(final_sql, params)
        return dict(self.env.cr.fetchall())

    def _compute_procurement_qty(self, demand_data):
        """
        Compute procurement quantities based on demand.

        If replenish_limit_to_free_qty is False, procurement qty equals demand.
        If replenish_limit_to_free_qty is True, procurement qty is limited to the
        free quantity at the source location.

        These two steps — availability check and qty decision — are intentionally
        kept together: splitting them across separate transactions could lead to
        over-replenishment when multiple orderpoints share the same source location.

        :return: dict {product_id: procurement_qty}
        """
        if not self.replenish_limit_to_free_qty:
            return demand_data

        # Resolve products from demand keys to pass to the availability query.
        products = self._product_model.browse(demand_data.keys())
        qty_available_data = self._compute_available_quantities(products)

        return {
            product_id: min(
                demand_data[product_id], qty_available_data.get(product_id, 0)
            )
            for product_id in demand_data
        }

    def _prepare_procurement_vals(self):
        """
        Prepare values for procurement creation.
        """
        self.ensure_one()
        return {
            "route_ids": self.route_id,
            "date_deadline": False,
            "warehouse_id": self.location_id.warehouse_id,
            "group_id": self.group_id,
            "priority": self.priority or "0",
            "location_orderpoint_id": self.id,
        }

    def _prepare_procurement(self, product, qty, date_planned, proc_vals):
        self.ensure_one()
        proc_vals = copy(proc_vals)
        proc_vals.update(
            {
                "date_planned": date_planned or fields.Datetime.now(),
            }
        )
        return self.env["procurement.group"].Procurement(
            product,
            qty,
            product.uom_id,
            self.location_id,
            self.name,
            self.name,
            self.company_id,
            proc_vals,
        )

    def _execute_run_procurements(self, procurement_values):
        """
        Execute the procurements synchronously and return the created moves.

        This is the sole synchronous execution path, shared by:
        - AUTO orderpoints (always, since they already run inside a queue.job)
        - CRON / MANUAL orderpoints when proc_run_async is False
        - The delayed job _fulfill_procurement() for async cron/manual runs

        :param procurement_values: list of namedtuple Procurement objects
        :return: recordset of created stock.move
        """
        with MovesTouchTracker() as tracker:
            self.env["procurement.group"].with_context(from_orderpoint=True).run(
                procurement_values, raise_user_error=False
            )
            return self.env["stock.move"].browse(tracker.get_ids()).exists()

    # -------------------------------------------------------------------------
    # Replenishment delegation to delayed jobs (cron / manual only)
    # -------------------------------------------------------------------------

    def _must_delay_procurement_run(self):
        """
        Returns True when per-product procurement fulfillment should be
        deferred to queue.jobs rather than run synchronously.

        Restricted to 'cron' and 'manual' triggers (via proc_run_async).
        AUTO orderpoints must never reach this branch: they are already
        executing inside a queue.job enqueued by stock.move via
        _enqueue_run_replenishment(). Delaying again would create a
        superfluous second job chain without any benefit.
        """
        self.ensure_one()
        if self.trigger == "auto":
            return False
        return self.proc_run_async

    def _enqueue_fulfill_procurement(self, product_id, demand_qty, **job_options):
        """
        Enqueue a delayed job to fulfill the procurement for one product.

        Used exclusively by cron and manual triggers when proc_run_async is True.
        The actual work is performed by _fulfill_procurement().

        :param product_id: ID of the product to fulfill
        :param demand_qty: demanded quantity as computed by _compute_demand()
        :param job_options: extra options forwarded to the job (priority, …)
        :return: a Job instance (not yet delayed — caller must call .delay())
        """
        job_options = job_options.copy()
        job_options.setdefault(
            "description",
            _(
                "Try to fulfill procurement for product %(product_name)s in location "
                "%(location_name)s for a demand of %(demand_qty)s",
                product_name=self.env["product.product"]
                .browse(product_id)
                .display_name,
                location_name=self.location_id.display_name,
                demand_qty=demand_qty,
            ),
        )
        job_options.setdefault("identity_key", identity_exact)
        delayable = self.delayable(**job_options)
        return delayable._fulfill_procurement(product_id, demand_qty)

    def _fulfill_procurement(self, product_id, demand_qty):
        """
        Fulfill the procurement for a single product from a known demand quantity.

        Encapsulates the three steps that must remain atomic:
        - compute the actual qty to procure (available qty check vs demand)
        - build the Procurement object
        - execute it and post-process the created moves

        This is the queue.job entry point for async cron/manual runs, but its
        contract is independent of that context. It can equally be called
        synchronously when needed.

        When proc_run_async is True, one job per (orderpoint, product) is
        created after _compute_demand(), so the number of jobs is bounded by
        the number of products with actual demand — not the total product
        catalogue.

        :param product_id: ID of the product to fulfill
        :param demand_qty: demanded quantity as computed by _compute_demand()
        :return: a human-readable summary string (stored as the job result)
        """
        procurement_data = self._compute_procurement_qty({product_id: demand_qty})
        if not procurement_data:
            product = self.env["product.product"].browse(product_id)
            return (
                f"No quantity available at source for {product.display_name} "
                f"in {self.display_name} (demand was {demand_qty})"
            )

        procurements = self._build_procurements(procurement_data)
        if not procurements:
            product = self.env["product.product"].browse(product_id)
            return (
                f"No procurements could be built for {product.display_name} "
                f"in {self.display_name}"
            )

        result = self._execute_run_procurements(procurements)
        self._after_replenishment(result)
        return f"{len(result)} replenishment moves created for {self.display_name}"

    # -------------------------------------------------------------------------
    # Post-processing of replenishment moves
    # -------------------------------------------------------------------------

    def _after_replenishment(self, replenishment_moves):
        """
        Assigns generated replenishment moves.
        """
        self._assign_replenishment_moves(
            replenishment_moves.filtered(lambda m: m.state != "assigned")
        )
        picking_priority_to_update = self.env["stock.picking"]
        for move in replenishment_moves.sudo():
            new_priority = move.location_orderpoint_id.priority
            if move.priority != new_priority:
                move.priority = new_priority
                picking_priority_to_update |= move.picking_id
        for picking in picking_priority_to_update:
            new_priority = max(
                picking.move_ids.filtered(lambda m: m.state != "cancel").mapped(
                    "priority"
                )
            )
            if picking.priority != new_priority:
                # we want to avoid to override the individual move priority by the
                # picking priority, so we protect the priority field on the
                # picking's moves
                with self.env.protecting(
                    [self.env["stock.move"]._fields["priority"]], picking.move_ids
                ):
                    picking.priority = new_priority

        return self._strategy_model._after_run_replenishment(self, replenishment_moves)

    def _assign_replenishment_moves(self, moves_to_assign):
        """Assigns moves created by the orderpoints"""
        for moves_chunk in split_every(100, moves_to_assign.ids):
            self.env["stock.move"].browse(moves_chunk)._action_assign()
        return moves_to_assign

    # -------------------------------------------------------------------------
    # Cache lifecycle
    # -------------------------------------------------------------------------

    def _clear_caches(self):
        self._get_ids_by_parent_path.clear_cache(self)
        self._get_consuming_moves_domain.clear_cache(self)
        self._get_supplying_moves_domain.clear_cache(self)
        self._get_src_domains.clear_cache(self)
        self._get_dest_domains.clear_cache(self)

    @api.model_create_multi
    def create(self, vals_list):
        self._clear_caches()
        return super().create(vals_list)

    def write(self, vals):
        self._clear_caches()
        return super().write(vals)

    def unlink(self):
        self._clear_caches()
        return super().unlink()
